name: Build and Push Backend & Frontend Images

on:
  push:
    branches:
      - development

jobs:
  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: backend
            context: backend
            dockerfile: backend/Dockerfile
          - name: frontend
            context: frontend
            dockerfile: frontend/Dockerfile

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.name }} image
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/demand-note-${{ matrix.name }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/demand-note-${{ matrix.name }}:${{ github.sha }}

  trigger-deploy:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Coolify Deploy
        run: |
          curl -X POST "http://143.244.141.58:8000/api/v1/deploy?uuid=zb433vr4scqn2wh7jhok6lfn&force=false"
